/** @format */
export const HAPPYCHAT_USER_CURRENT_SET = 'HAPPYCHAT_USER_CURRENT_SET';
export const HAPPYCHAT_USER_GROUPS_SET = 'HAPPYCHAT_USER_GROUPS_SET';
export const HAPPYCHAT_USER_LOCALE_SET = 'HAPPYCHAT_USER_LOCALE_SET';
