/** @format */

/**
 * Any new action type should be added to the set of exports below, with the
 * value mirroring its exported name.
 *
 * Please keep this list alphabetized!
 *
 */

export const HAPPYCHAT_ASSETS_LOADED = 'HAPPYCHAT_ASSETS_LOADED';
export const HAPPYCHAT_BLUR = 'HAPPYCHAT_BLUR';
export const HAPPYCHAT_FOCUS = 'HAPPYCHAT_FOCUS';
export const HAPPYCHAT_IO_INIT = 'HAPPYCHAT_IO_INIT';
export const HAPPYCHAT_IO_RECEIVE_ACCEPT = 'HAPPYCHAT_IO_RECEIVE_ACCEPT';
export const HAPPYCHAT_IO_RECEIVE_CONNECT = 'HAPPYCHAT_IO_RECEIVE_CONNECT';
export const HAPPYCHAT_IO_RECEIVE_DISCONNECT = 'HAPPYCHAT_IO_RECEIVE_DISCONNECT';
export const HAPPYCHAT_IO_RECEIVE_ERROR = 'HAPPYCHAT_IO_RECEIVE_ERROR';
export const HAPPYCHAT_IO_RECEIVE_INIT = 'HAPPYCHAT_IO_RECEIVE_INIT';
export const HAPPYCHAT_IO_RECEIVE_MESSAGE = 'HAPPYCHAT_IO_RECEIVE_MESSAGE';
export const HAPPYCHAT_IO_RECEIVE_RECONNECTING = 'HAPPYCHAT_IO_RECEIVE_RECONNECTING';
export const HAPPYCHAT_IO_RECEIVE_STATUS = 'HAPPYCHAT_IO_RECEIVE_STATUS';
export const HAPPYCHAT_IO_RECEIVE_TOKEN = 'HAPPYCHAT_IO_RECEIVE_TOKEN';
export const HAPPYCHAT_IO_RECEIVE_UNAUTHORIZED = 'HAPPYCHAT_IO_RECEIVE_UNAUTHORIZED';
export const HAPPYCHAT_IO_REQUEST_TRANSCRIPT = 'HAPPYCHAT_IO_REQUEST_TRANSCRIPT';
export const HAPPYCHAT_IO_REQUEST_FALLBACK_TICKET = 'HAPPYCHAT_IO_REQUEST_FALLBACK_TICKET';
export const HAPPYCHAT_IO_REQUEST_FALLBACK_TICKET_RECEIVE =
	'HAPPYCHAT_IO_REQUEST_FALLBACK_TICKET_RECEIVE';
export const HAPPYCHAT_IO_REQUEST_FALLBACK_TICKET_TIMEOUT =
	'HAPPYCHAT_IO_REQUEST_FALLBACK_TICKET_TIMEOUT';
export const HAPPYCHAT_IO_REQUEST_TRANSCRIPT_RECEIVE = 'HAPPYCHAT_IO_REQUEST_TRANSCRIPT_RECEIVE';
export const HAPPYCHAT_IO_REQUEST_TRANSCRIPT_TIMEOUT = 'HAPPYCHAT_IO_REQUEST_TRANSCRIPT_TIMEOUT';
export const HAPPYCHAT_IO_SEND_MESSAGE_EVENT = 'HAPPYCHAT_IO_SEND_MESSAGE_EVENT';
export const HAPPYCHAT_IO_SEND_MESSAGE_LOG = 'HAPPYCHAT_IO_SEND_MESSAGE_LOG';
export const HAPPYCHAT_IO_SEND_MESSAGE_MESSAGE = 'HAPPYCHAT_IO_SEND_MESSAGE_MESSAGE';
export const HAPPYCHAT_IO_SEND_MESSAGE_USERINFO = 'HAPPYCHAT_IO_SEND_MESSAGE_USERINFO';
export const HAPPYCHAT_IO_SEND_PREFERENCES = 'HAPPYCHAT_IO_SEND_PREFERENCES';
export const HAPPYCHAT_IO_SEND_TYPING = 'HAPPYCHAT_IO_SEND_TYPING';
export const HAPPYCHAT_MINIMIZING = 'HAPPYCHAT_MINIMIZING';
export const HAPPYCHAT_OPEN = 'HAPPYCHAT_OPEN';
export const HAPPYCHAT_SET_CURRENT_MESSAGE = 'HAPPYCHAT_SET_CURRENT_MESSAGE';
export const HAPPYCHAT_USER_CURRENT_SET = 'HAPPYCHAT_USER_CURRENT_SET';
export const HAPPYCHAT_USER_GROUPS_SET = 'HAPPYCHAT_USER_GROUPS_SET';
export const HAPPYCHAT_USER_LOCALE_SET = 'HAPPYCHAT_USER_LOCALE_SET';
