/** @format */
export const HAPPYCHAT_CHAT_EVENT_RECEIVE = 'HAPPYCHAT_CHAT_EVENT_RECEIVE';
export const HAPPYCHAT_CHAT_MESSAGE_SEND = 'HAPPYCHAT_CHAT_MESSAGE_SEND';
export const HAPPYCHAT_CHAT_MESSAGE_SET = 'HAPPYCHAT_CHAT_MESSAGE_SET';
export const HAPPYCHAT_CHAT_STATUS_SET = 'HAPPYCHAT_CHAT_STATUS_SET';
export const HAPPYCHAT_CHAT_TRANSCRIPT_RECEIVE = 'HAPPYCHAT_CHAT_STATUS_SET';
export const HAPPYCHAT_CHAT_TRANSCRIPT_REQUEST = 'HAPPYCHAT_CHAT_TRANSCRIPT_REQUEST';
export const HAPPYCHAT_CHAT_USERINFO_SEND = 'HAPPYCHAT_CHAT_USERINFO_SEND';
export const HAPPYCHAT_UI_BLUR = 'HAPPYCHAT_UI_BLUR';
export const HAPPYCHAT_UI_FOCUS = 'HAPPYCHAT_UI_FOCUS';
export const HAPPYCHAT_UI_MINIMIZING = 'HAPPYCHAT_UI_MINIMIZING';
export const HAPPYCHAT_UI_OPEN = 'HAPPYCHAT_UI_OPEN';
export const HAPPYCHAT_USER_GEOLOCATION_SET = 'HAPPYCHAT_USER_GEOLOCATION_SET';
export const HAPPYCHAT_USER_LOCALE_SET = 'HAPPYCHAT_USER_LOCALE_SET';
export const HAPPYCHAT_USER_CURRENT_SET = 'HAPPYCHAT_USER_CURRENT_SET';
